### ISSUE TITLE
Container exits under podman.

### ISSUE THREAD

**Issue by tetricky** [sando38/docker-ejabberd-multiarch#1]
I'm starting to try to get to know this image, as i am hoping to be able to run an ejabberd server under podman with it.

Simply trying to run the container, without any volumes mounted and with no parameters set, fails with the following error: ```[FATAL tini (2)] exec run.sh failed: No such file or directory```

Inspecting the dockerfile, I noted the fiollowing:

```#    && mv $HOME/scripts/* /usr/local/bin \```

Should that be uncommented to copy the scripts into the correct place?

**Comment by tetricky** [comment]
I have done a local (podman) build of the container with the above statement included (not commented out), and the container now runs, and the startup script executes ```Starting ejabberd multiarch container with startup script``` and appears to complete correctly.

Thank you for your work on this. It's very much something that I will find useful. If I can manage to correctly set it up for my circumstances (podman, caddy reverse proxy, ldap authentication).

**Comment by sando38** [comment]
Thanks, I will have a look and provide feedback.

**Comment by sando38** [comment]
Yes, from inspecting the Dockerfile, you are right. This should not be commented out. I will fix it as it is most likely also not working in Docker or other container environments.
