### ISSUE TITLE
Host setting leads to configuration file error. Networking in k8s?

### ISSUE THREAD

**Issue by tetricky** [sando38/docker-ejabberd-multiarch#2]
A small issue. In setting the ```XMPP_DOMAIN3``` environment variable, for some reason two copies of the respective host are copied into the config (ejabberd.yml) file.

Which leads to an error.

I have given up trying to get this running under podman. The complex networking has me beat.

I have seen somewhere that you have a working installation under k8s. I'm going to have a go myself (k3s cluster). In terms of exposing services to the outside world I can foresee problems.

I don't suppose that you have any config examples for k8s that you might be willing to share?

**Comment by sando38** [comment]
hello,

yes, that is a bug. I have fixed it in the last commit. thanks!

> I have given up trying to get this running under podman. The complex networking has me beat.

Where a you stucked, maybe I can help.

> I have seen somewhere that you have a working installation under k8s. I'm going to have a go myself (k3s cluster). In terms of exposing services to the outside world I can foresee problems.

I am using a slightly adjusted configuration of the example provided in this repo in a k3s setup. I may also help here, in case you have problems.
